
services:

  postgres:
    image: postgres:17
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: movwe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - movwe-network

#  mongodb:
#    image: mongo:6
#    container_name: mongo-db
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - movwe-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movwe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

#      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/mydatabase
    depends_on:
      - postgres
#      - mongodb
    networks:
      - movwe-network

volumes:
  postgres-data:
#      mongo-data:
networks:
  movwe-network: