-- Database scheme
CREATE SCHEMA IF NOT EXISTS public;

-- Sequence for employees and clients tables --
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 50;

-- Tables --
CREATE TABLE clients (
    id BIGINT PRIMARY KEY DEFAULT nextval('user_seq'),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    creation_date BIGINT,
    username VARCHAR(255) UNIQUE,
    state VARCHAR(255),
    city VARCHAR(255),
    street VARCHAR(255),
    zip VARCHAR(50),
    phone VARCHAR(255)
);

CREATE TABLE employees (
    id BIGINT PRIMARY KEY DEFAULT nextval('user_seq'),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    creation_date BIGINT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role VARCHAR(40) NOT NULL CHECK (role IN ('ADMIN', 'EDITOR'))
);

CREATE TABLE movies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NOT NULL,
    title VARCHAR(255),
    description VARCHAR(255),
    year_of_release VARCHAR(4),
    trailer_url VARCHAR(255),
    type VARCHAR(50) CHECK (type IN ('MOVIE', 'SERIES')),
    genre VARCHAR(50) CHECK (genre IN ('ACTION','COMEDY','DRAMA','FANTASY','HORROR','ROMANCE','THRILLER')),
    creation_date BIGINT,
    CONSTRAINT fk_movies_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE client_friends (
    client_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (client_id, friend_id),
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (friend_id) REFERENCES clients(id)
);

-- Indexing email columns --
CREATE INDEX idx_clients_email ON clients (email);
CREATE INDEX idx_employees_email ON employees (email);
