-- Schema
CREATE SCHEMA IF NOT EXISTS public;

-- Sequence
CREATE SEQUENCE person_seq START WITH 1 INCREMENT BY 50;

-- Users table
CREATE TABLE users (
    id BIGINT PRIMARY KEY DEFAULT nextval('person_seq'),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    salt VARCHAR(255) NOT NULL,
    identifier VARCHAR(255) NOT NULL UNIQUE,
    creation_date BIGINT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birth_date BIGINT,
    state VARCHAR(255),
    city VARCHAR(255),
    street VARCHAR(255),
    zip VARCHAR(255),
    phone VARCHAR(255)
);

-- Moderators table
CREATE TABLE moderators (
    id BIGINT PRIMARY KEY DEFAULT nextval('person_seq'),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'EDITOR')),
    active BOOLEAN DEFAULT TRUE,
    salt VARCHAR(255) NOT NULL,
    identifier VARCHAR(255) NOT NULL UNIQUE,
    creation_date BIGINT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

-- Movies table
CREATE TABLE movies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255),
    description VARCHAR(255),
    year_of_release INTEGER,
    trailer_url VARCHAR(255),
    type VARCHAR(255) CHECK (type IN ('MOVIE','SERIES','DOCUMENTARY','YOUTUBE_VIDEO','YOUTUBE_SHORT','OTHER')),
    genre VARCHAR(255) CHECK (genre IN ('ACTION','ADVENTURE','ANIMATION','COMEDY','CRIME','DRAMA','FANTASY','HISTORICAL','HORROR','MYSTERY','ROMANCE','SCIENCE_FICTION','THRILLER','WESTERN')),
    creation_date BIGINT,
    CONSTRAINT fk_movies_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- User friends join table
CREATE TABLE user_friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

-- Indexes
CREATE INDEX idx_users_username ON users(username);
